version: '3'
services:
  app:
    image: env-settings-net
    build: .
    ports:
      - 8000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGO_HOST=localhost
      - MONGO_PORT=27017
      - MONGO_DATABASE=env-settings-net-dev